### ISSUE TITLE
Expression all the things!

### ISSUE THREAD

**Issue by joews** [joews/prequel#52]
See #65.

Some special-case productions (`operand` and `field_expression`) are used in place of full `expressions`. That was pragmatic for getting started (because it meant less left-recursion to avoid) but now is the time to fix it.
- [x] Grammar: Replace `operand` with `expression`
- [x] Grammar: Replace `field_expression` with `expression` (which also includes aggregate expressions).
- [ ] Grammar: `ORDER BY` expression
- [ ] Grammar: `GROUP BY` expression
- [ ] Grammar: `LIMIT` expression
- [ ] Runtime: make it work again!

We will follow the [sqlite expression grammar](https://www.sqlite.org/lang_expr.html).

**Comment by jwhitfieldseed** [comment]
It should be possible to combine the `field_expression` and `operand` productions at this point.
